/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projetosingleton01;

/**
 *
 * @author Giu
 */
public class MuralGeral extends javax.swing.JFrame {

    /**
     * Creates new form MuralGeral
     */
    
    //Atributos da classe Mural
    Mural mural01 = null;
    Mural mural02 = null; 
    
    public MuralGeral() {
        initComponents();
        jButtonInserirMural01.setEnabled(false);
        jButtonInserirMural02.setEnabled(false);
        jTextAreaObjeto2.setEnabled(false);
        jTextAreaObjeto1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldTexto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObjeto2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaObjeto1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonCriarObjetos = new javax.swing.JButton();
        jButtonInserirMural01 = new javax.swing.JButton();
        jButtonInserirMural02 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Texto");

        jTextAreaObjeto2.setColumns(20);
        jTextAreaObjeto2.setRows(5);
        jScrollPane1.setViewportView(jTextAreaObjeto2);

        jTextAreaObjeto1.setColumns(20);
        jTextAreaObjeto1.setRows(5);
        jScrollPane2.setViewportView(jTextAreaObjeto1);

        jLabel2.setText("Mural Objeto 01");

        jLabel3.setText("Mural Objeto 02");

        jButtonCriarObjetos.setText("Criar Objetos Mural");
        jButtonCriarObjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarObjetosActionPerformed(evt);
            }
        });

        jButtonInserirMural01.setText("Inserir texto Mural 01");
        jButtonInserirMural01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirMural01ActionPerformed(evt);
            }
        });

        jButtonInserirMural02.setText("Inserir texto Mural 02");
        jButtonInserirMural02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirMural02ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 224, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel2))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 224, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jButtonInserirMural01)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jButtonInserirMural02))
                            .add(jTextFieldTexto)))))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButtonCriarObjetos)
                .add(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jButtonCriarObjetos)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTextFieldTexto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonInserirMural01)
                    .add(jButtonInserirMural02))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jLabel3))
                .add(1, 1, 1)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCriarObjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarObjetosActionPerformed
        // TODO add your handling code here:
        mural01 =   Mural.getMural("Mural 01");
        mural02 =   Mural.getMural("Mural 02");
        jButtonInserirMural01.setEnabled(true);
        jButtonInserirMural02.setEnabled(true);
        jButtonCriarObjetos.setEnabled(false);
    }//GEN-LAST:event_jButtonCriarObjetosActionPerformed

    private void jButtonInserirMural01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirMural01ActionPerformed
        // TODO add your handling code here:
        mural01.setTexto(jTextFieldTexto.getText());
        jTextAreaObjeto1.setText(mural01.getTexto());
        jTextFieldTexto.setText("");
    }//GEN-LAST:event_jButtonInserirMural01ActionPerformed

    private void jButtonInserirMural02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirMural02ActionPerformed
        // TODO add your handling code here:
        mural02.setTexto(jTextFieldTexto.getText());
        jTextAreaObjeto2.setText(mural02.getTexto());
        jTextFieldTexto.setText("");
    }//GEN-LAST:event_jButtonInserirMural02ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MuralGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MuralGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MuralGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MuralGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MuralGeral().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCriarObjetos;
    private javax.swing.JButton jButtonInserirMural01;
    private javax.swing.JButton jButtonInserirMural02;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaObjeto1;
    private javax.swing.JTextArea jTextAreaObjeto2;
    private javax.swing.JTextField jTextFieldTexto;
    // End of variables declaration//GEN-END:variables
}
